use crate::server::AppState;
use axum::{
    extract::{Json, State},
    http::StatusCode,
    response::{
        IntoResponse, Response,
        sse::{Event as SseEvent, Sse},
    },
};
use clarity_core::agent::{
    AgentController, ControllerEvent, Message as AgentMessage, MessageRole, Op,
    driver::ConversationChatDriver,
};
use futures::{Stream, stream};
use serde::{Deserialize, Serialize};
use std::convert::Infallible;
use std::sync::Arc;
use tokio::sync::mpsc::UnboundedReceiver;
use tracing::{debug, info, warn};

use crate::handlers::AgentHandle;

// ==================== 健康检查 ====================

/// Health check response payload.
#[derive(Serialize)]
pub struct HealthResponse {
    /// Service status, e.g. `"healthy"`.
    pub status: String,
    /// Crate version running the gateway.
    pub version: String,
    /// Current UTC timestamp in RFC 3339 format.
    pub timestamp: String,
}

/// Return a simple health status for load balancers and watchdogs.
pub async fn health_check() -> impl IntoResponse {
    debug!("Health check requested");
    let response = HealthResponse {
        status: "healthy".to_string(),
        version: env!("CARGO_PKG_VERSION").to_string(),
        timestamp: chrono::Utc::now().to_rfc3339(),
    };
    (StatusCode::OK, Json(response))
}

/// Return current connection metrics for monitoring.
pub async fn health_metrics(State(state): State<Arc<AppState>>) -> impl IntoResponse {
    let snapshot = state.metrics.snapshot();
    (StatusCode::OK, Json(snapshot))
}

// ==================== Chat Completions ====================

/// OpenAI-compatible chat completion request.
// Intentionally retained: temperature/max_tokens are reserved for future provider passthrough.
#[allow(dead_code)]
#[derive(Debug, Deserialize)]
pub struct ChatCompletionRequest {
    /// Model alias or identifier requested by the client.
    pub model: String,
    /// Conversation messages for the completion.
    pub messages: Vec<Message>,
    /// Whether to stream the response as SSE.
    #[serde(default)]
    pub stream: bool,
    /// Optional sampling temperature.
    #[serde(default)]
    pub temperature: Option<f32>,
    /// Optional maximum token limit.
    #[serde(default)]
    pub max_tokens: Option<u32>,
    /// Optional session ID for persisting the conversation.
    /// If provided, the assistant's reply will be appended to the session.
    #[serde(default)]
    pub session_id: Option<String>,
}

/// A single chat message in the OpenAI-compatible API.
#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct Message {
    /// Message role: `system`, `user`, `assistant`, or `tool`.
    pub role: String,
    /// Message content.
    pub content: String,
}

/// OpenAI-compatible chat completion response.
#[derive(Serialize)]
pub struct ChatCompletionResponse {
    /// Unique completion identifier.
    pub id: String,
    /// Object type, e.g. `"chat.completion"`.
    pub object: String,
    /// Unix timestamp of creation.
    pub created: i64,
    /// Model identifier echoed from the request.
    pub model: String,
    /// Completion choices generated by the model.
    pub choices: Vec<Choice>,
    /// Token usage summary.
    pub usage: Usage,
    /// Optional session ID if persistence was requested.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

/// A single choice in a chat completion response.
#[derive(Serialize)]
pub struct Choice {
    /// Index of this choice in the response.
    pub index: u32,
    /// Generated message.
    pub message: Message,
    /// Reason the model stopped generating.
    pub finish_reason: String,
}

/// Token usage summary for a chat completion.
#[derive(Serialize)]
pub struct Usage {
    /// Tokens in the prompt.
    pub prompt_tokens: u32,
    /// Tokens generated by the model.
    pub completion_tokens: u32,
    /// Total tokens consumed.
    pub total_tokens: u32,
}

/// Build an OpenAI-compatible SSE stream from agent controller events.
///
/// The `on_complete` callback is invoked with the final assistant message when
/// a [`ControllerEvent::Complete`] is observed. It is typically used to persist
/// the turn to a session or thread store without blocking the SSE stream.
pub(crate) fn chat_completion_sse_stream<F>(
    model: String,
    event_rx: UnboundedReceiver<ControllerEvent>,
    on_complete: F,
) -> Sse<impl Stream<Item = Result<SseEvent, Infallible>>>
where
    F: Fn(String) + Send + Sync + 'static,
{
    let created = chrono::Utc::now().timestamp();
    let id = format!("chatcmpl-{}", uuid::Uuid::new_v4().simple());
    let on_complete = Arc::new(on_complete);

    let sse_stream = stream::unfold((event_rx, 0u8), move |(mut rx, step)| {
        let model = model.clone();
        let id = id.clone();
        let on_complete = on_complete.clone();
        async move {
            if step == 2 {
                return None;
            }
            if step == 1 {
                let event = SseEvent::default().data("[DONE]");
                return Some((Ok::<_, Infallible>(event), (rx, 2)));
            }
            match rx.recv().await {
                Some(ControllerEvent::Chunk(text)) => {
                    let data = serde_json::json!({
                        "id": &id,
                        "object": "chat.completion.chunk",
                        "created": created,
                        "model": &model,
                        "choices": [{"index":0,"delta":{"content":text},"finish_reason":null}]
                    });
                    let event = SseEvent::default().data(data.to_string());
                    Some((Ok(event), (rx, 0)))
                }
                Some(ControllerEvent::ToolCallStart {
                    id: tc_id,
                    name,
                    arguments,
                }) => {
                    let args_str = arguments.to_string();
                    let data = serde_json::json!({
                        "id": &id,
                        "object": "chat.completion.chunk",
                        "created": created,
                        "model": &model,
                        "choices": [{
                            "index": 0,
                            "delta": {
                                "tool_calls": [{
                                    "index": 0,
                                    "id": tc_id,
                                    "type": "function",
                                    "function": {
                                        "name": name,
                                        "arguments": args_str
                                    }
                                }]
                            },
                            "finish_reason": null
                        }]
                    });
                    let event = SseEvent::default().data(data.to_string());
                    Some((Ok(event), (rx, 0)))
                }
                Some(ControllerEvent::ToolResult { id: tc_id, result }) => {
                    let data = serde_json::json!({
                        "object": "clarity.event",
                        "type": "tool_result",
                        "id": tc_id,
                        "result": result
                    });
                    let event = SseEvent::default().data(data.to_string());
                    Some((Ok(event), (rx, 0)))
                }
                Some(ControllerEvent::StepBegin { tool_name }) => {
                    let data = serde_json::json!({
                        "object": "clarity.event",
                        "type": "step_begin",
                        "tool_name": tool_name
                    });
                    let event = SseEvent::default().data(data.to_string());
                    Some((Ok(event), (rx, 0)))
                }
                Some(ControllerEvent::Complete(final_text)) => {
                    on_complete(final_text.clone());
                    let data = serde_json::json!({
                        "id": &id,
                        "object": "chat.completion.chunk",
                        "created": created,
                        "model": &model,
                        "choices": [{"index":0,"delta":{},"finish_reason":"stop"}]
                    });
                    let event = SseEvent::default().data(data.to_string());
                    Some((Ok(event), (rx, 1)))
                }
                Some(ControllerEvent::Error(_)) | None => {
                    let data = serde_json::json!({
                        "id": &id,
                        "object": "chat.completion.chunk",
                        "created": created,
                        "model": &model,
                        "choices": [{"index":0,"delta":{},"finish_reason":"stop"}]
                    });
                    let event = SseEvent::default().data(data.to_string());
                    Some((Ok(event), (rx, 1)))
                }
            }
        }
    });

    Sse::new(sse_stream)
}

/// OpenAI-compatible chat completions endpoint.
///
/// Supports both streaming (SSE) and non-streaming responses, with optional
/// session persistence.
pub async fn chat_completions(
    State(state): State<Arc<AppState>>,
    Json(req): Json<ChatCompletionRequest>,
) -> Response {
    info!(
        "Chat completion request: model={}, stream={}",
        req.model, req.stream
    );
    debug!("Request messages: {:?}", req.messages);

    // Acquire concurrency permit — prevents unbounded spawn under load.
    let _permit = match state.chat_sem.acquire().await {
        Ok(p) => p,
        Err(_) => {
            return (
                StatusCode::SERVICE_UNAVAILABLE,
                Json(serde_json::json!({
                    "error": "Gateway is at maximum concurrency limit"
                })),
            )
                .into_response();
        }
    };

    let _ = state.session_store.record_request().await;

    // Resolve or create session id
    let session_id = req
        .session_id
        .clone()
        .or_else(|| Some(format!("http-{}", uuid::Uuid::new_v4().simple())));

    // Validate that there is at least one user message
    let has_user = req.messages.iter().any(|m| m.role == "user");
    if !has_user {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({
                "error": "No user message found in request"
            })),
        )
            .into_response();
    }

    // Create a per-request AgentController so that streaming events are isolated.
    let agent = state.clone_agent();

    // Security: log a warning when the agent is in Yolo mode via Gateway,
    // since HTTP clients cannot interactively approve dangerous tool calls.
    if agent.approval_mode() == clarity_core::approval::ApprovalMode::Yolo {
        warn!(
            "Gateway chat_completions running with Yolo approval mode — \
             tool calls will execute without user confirmation"
        );
    }

    // Build the internal message list:
    // 1. Agent system prompt
    // 2. Session history (if session_id provided and session exists)
    // 3. All non-system messages from the request
    let mut messages: Vec<AgentMessage> = vec![AgentMessage::system(agent.build_system_prompt())];

    // Load session history if a session_id was explicitly provided
    if let Some(ref sid) = req.session_id {
        match state.session_store.load_session(sid).await {
            Ok(history) => {
                for msg in history {
                    let role = match msg.role.as_str() {
                        "user" => MessageRole::User,
                        "assistant" => MessageRole::Assistant,
                        "tool" => MessageRole::Tool,
                        _ => MessageRole::User,
                    };
                    messages.push(AgentMessage {
                        role,
                        content: msg.content,
                        tool_calls: msg
                            .tool_calls
                            .map(|s| serde_json::from_str(&s).unwrap_or_default()),
                        tool_call_id: msg.tool_call_id,
                    });
                }
            }
            Err(e) => {
                debug!("Failed to load session {}: {}. Starting fresh.", sid, e);
            }
        }
    }

    for msg in &req.messages {
        if msg.role == "system" {
            continue;
        }
        let role = match msg.role.as_str() {
            "user" => MessageRole::User,
            "assistant" => MessageRole::Assistant,
            "tool" => MessageRole::Tool,
            _ => MessageRole::User,
        };
        messages.push(AgentMessage {
            role,
            content: msg.content.clone(),
            tool_calls: None,
            tool_call_id: None,
        });
    }

    // Guard against providers that reject oversized request bodies (e.g. DeepSeek's
    // 2MB limit). Drop oldest non-system messages while keeping the current query.
    const MAX_BODY_BYTES: usize = 1_000_000;
    let original_count = messages.len();
    messages = truncate_messages_by_bytes(messages, MAX_BODY_BYTES);
    if messages.len() < original_count {
        warn!(
            "Truncated chat context from {} to {} messages to fit {} byte budget",
            original_count,
            messages.len(),
            MAX_BODY_BYTES
        );
    }

    // Pre-calculate token estimate before messages are moved into the controller.
    let prompt_tokens = messages.iter().map(|m| m.content.len()).sum::<usize>() as u32 / 4;

    let (event_tx, mut event_rx) = tokio::sync::mpsc::unbounded_channel::<ControllerEvent>();
    let driver = Arc::new(ConversationChatDriver {
        history: messages.clone(),
    });
    let (controller, op_tx) = AgentController::new_with_events(agent, event_tx, Some(driver));
    tokio::spawn(controller.run());

    let last_user_query = req
        .messages
        .iter()
        .rev()
        .find(|m| m.role == "user")
        .map(|m| m.content.clone())
        .unwrap_or_default();
    if let Err(e) = op_tx.send(Op::user_turn(last_user_query)) {
        return (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(serde_json::json!({
                "error": format!("Failed to start agent turn: {}", e)
            })),
        )
            .into_response();
    }

    if req.stream {
        // Clone session store for background persistence in streaming mode.
        let store = state.session_store.clone();
        let sid = session_id.clone();
        let last_user_content = req
            .messages
            .iter()
            .rev()
            .find(|m| m.role == "user")
            .map(|m| m.content.clone());

        let on_complete = move |final_text: String| {
            if let (Some(s), Some(uc)) = (sid.clone(), last_user_content.clone()) {
                let store = store.clone();
                tokio::spawn(async move {
                    let _ = store
                        .append_message(&s, &crate::session_store::SessionMessage::new("user", &uc))
                        .await;
                    let _ = store
                        .append_message(
                            &s,
                            &crate::session_store::SessionMessage::new("assistant", &final_text),
                        )
                        .await;
                });
            }
        };

        chat_completion_sse_stream(req.model.clone(), event_rx, on_complete).into_response()
    } else {
        // Non-streaming: accumulate chunks until Complete/Error.
        let mut content = String::new();
        let mut error_msg: Option<String> = None;
        while let Some(ev) = event_rx.recv().await {
            match ev {
                ControllerEvent::Chunk(chunk) => content.push_str(&chunk),
                ControllerEvent::Complete(final_text) => {
                    content = final_text;
                    break;
                }
                ControllerEvent::Error(e) => {
                    error_msg = Some(e);
                    break;
                }
                // Tool-calling events are not included in non-streaming text response.
                ControllerEvent::ToolCallStart { .. }
                | ControllerEvent::ToolResult { .. }
                | ControllerEvent::StepBegin { .. } => {}
            }
        }

        if let Some(e) = error_msg {
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({
                    "error": format!("Agent execution error: {}", e)
                })),
            )
                .into_response();
        }

        let completion_tokens = content.len() as u32 / 4;

        // Persist the turn to the session store (non-streaming)
        if let Some(ref sid) = session_id {
            if let Some(last_user) = req.messages.iter().rev().find(|m| m.role == "user") {
                let _ = state
                    .session_store
                    .append_message(
                        sid,
                        &crate::session_store::SessionMessage::new("user", &last_user.content),
                    )
                    .await;
            }
            let _ = state
                .session_store
                .append_message(
                    sid,
                    &crate::session_store::SessionMessage::new("assistant", &content),
                )
                .await;
        }

        let response = ChatCompletionResponse {
            id: format!("chatcmpl-{}", uuid::Uuid::new_v4().simple()),
            object: "chat.completion".to_string(),
            created: chrono::Utc::now().timestamp(),
            model: req.model,
            choices: vec![Choice {
                index: 0,
                message: Message {
                    role: "assistant".to_string(),
                    content,
                },
                finish_reason: "stop".to_string(),
            }],
            usage: Usage {
                prompt_tokens,
                completion_tokens,
                total_tokens: prompt_tokens + completion_tokens,
            },
            session_id,
        };

        (StatusCode::OK, Json(response)).into_response()
    }
}

/// Truncate message history to fit within a byte budget while preserving the
/// system prompt and the most recent user/assistant exchanges.
///
/// Providers such as DeepSeek reject request bodies larger than ~2MB. This
/// function drops oldest non-system messages until the total content size is
/// below `max_bytes`, always keeping the final user message.
pub fn truncate_messages_by_bytes(
    messages: Vec<AgentMessage>,
    max_bytes: usize,
) -> Vec<AgentMessage> {
    let total: usize = messages.iter().map(|m| m.content.len()).sum();
    if total <= max_bytes {
        return messages;
    }

    let mut result = Vec::new();
    let mut start = 0;
    if !messages.is_empty() && messages[0].role == MessageRole::System {
        result.push(messages[0].clone());
        start = 1;
    }

    let mut kept = messages[start..].to_vec();
    let budget = max_bytes.saturating_sub(result.iter().map(|m| m.content.len()).sum::<usize>());

    while kept.len() > 1 {
        let current: usize = kept.iter().map(|m| m.content.len()).sum();
        if current <= budget {
            break;
        }
        kept.remove(0);
    }

    result.extend(kept);
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn msg(role: MessageRole, content: &str) -> AgentMessage {
        AgentMessage {
            role,
            content: content.to_string(),
            tool_calls: None,
            tool_call_id: None,
        }
    }

    #[test]
    fn no_truncation_when_under_budget() {
        let messages = vec![
            msg(MessageRole::System, "sys"),
            msg(MessageRole::User, "hi"),
        ];
        let out = truncate_messages_by_bytes(messages.clone(), 1000);
        assert_eq!(out.len(), 2);
    }

    #[test]
    fn drops_oldest_non_system_messages() {
        let messages = vec![
            msg(MessageRole::System, "sys"),
            msg(MessageRole::User, "first"),
            msg(MessageRole::Assistant, "second"),
            msg(MessageRole::User, "last"),
        ];
        let out = truncate_messages_by_bytes(messages, 12);
        assert_eq!(out.len(), 2);
        assert_eq!(out[0].role, MessageRole::System);
        assert_eq!(out[1].content, "last");
    }

    #[test]
    fn keeps_last_message_even_if_oversized() {
        let messages = vec![
            msg(MessageRole::System, "sys"),
            msg(
                MessageRole::User,
                "a very long message that exceeds the budget",
            ),
        ];
        let out = truncate_messages_by_bytes(messages, 5);
        assert_eq!(out.len(), 2);
        assert_eq!(
            out[1].content,
            "a very long message that exceeds the budget"
        );
    }
}
