import { Theme } from "../theme.slint";

export component PretextLabel {
    in property <string> text: "";
    in property <string> font: "16px sans-serif";
    in property <length> requested-width: 200px;
    in property <color> text-color: Theme.text-primary;

    pure callback render-text(string, length, string, color) -> image;

    property <image> rendered-image: root.render-text(
        root.text,
        root.requested-width,
        root.font,
        root.text-color,
    );

    width: requested-width;
    height: rendered-image.height * 1px;

    Image {
        source: rendered-image;
        width: 100%;
        height: 100%;
    }
}
