#requires -Version 7.2
<#
.SYNOPSIS
    安装 git post-commit / post-push hook，在每次 commit/push 后自动运行技术债务扫描。
.DESCRIPTION
    只在本地 .git/hooks 下创建 hook 脚本，不修改仓库工作目录内容。
    需要用户手动运行一次。
.PARAMETER Model
    扫描使用的 Ollama 模型，默认 qwen2.5:7b。
.PARAMETER RepoRoot
    仓库根目录。
#>
[CmdletBinding()]
param(
    [string]$Model = 'qwen2.5:7b',
    [string]$RepoRoot = (Resolve-Path "$PSScriptRoot/..").Path
)

$ErrorActionPreference = 'Stop'

$HooksDir = Join-Path $RepoRoot '.git' 'hooks'
if (-not (Test-Path $HooksDir)) {
    throw "未找到 .git/hooks 目录：$HooksDir"
}

$scanScript = Resolve-Path (Join-Path $RepoRoot 'scripts' 'tech-debt-scan.ps1')

function Install-Hook {
    param([string]$HookName)
    $hookPath = Join-Path $HooksDir $HookName
    $hookScript = $scanScript -replace '\\', '/'
    $content = @"
#!/bin/sh
# Auto-generated by install-tech-debt-hooks.ps1
pwsh -NoProfile -ExecutionPolicy Bypass -File "$hookScript" -Model $Model
"@

    Set-Content -Path $hookPath -Value $content -Encoding UTF8 -NoNewline
    # Git for Windows 的 MSYS2 环境需要可执行权限
    & chmod +x $hookPath
    Write-Host "已安装 $hookPath" -ForegroundColor Green
}

Install-Hook -HookName 'post-commit'
Install-Hook -HookName 'post-push'

Write-Host "`n安装完成。每次 commit/push 后会自动调用：" -ForegroundColor Cyan
Write-Host "  $scanScript -Model $Model" -ForegroundColor Gray
Write-Host "`n卸载：删除 .git/hooks/post-commit 和 .git/hooks/post-push" -ForegroundColor Gray
