#!/usr/bin/env python3
"""HTTPS/WSS reverse proxy for Clarity Gateway.

Forwards HTTPS/WSS traffic on port 8443 to the Gateway HTTP/WS on port 18790.
Uses the certificate pair generated by scripts/generate_local_ca.py:

    .clarity/localhost.crt   server certificate (signed by local CA)
    .clarity/localhost.key   server private key

Clients that install .clarity/local-ca.crt will trust this server without
self-signed certificate warnings.

Requires: aiohttp

Usage:
    python scripts/generate_local_ca.py   # one-time
    python scripts/tls_reverse_proxy.py

Then open:
    https://localhost:8443/health
    wss://localhost:8443/openclaw/ws

For public/production access, replace the local CA with a real certificate
(e.g. Let's Encrypt via Caddy) or use a tunnel service.
"""

import asyncio
import ssl
import sys
from pathlib import Path

try:
    import aiohttp
    from aiohttp import web, WSMsgType
    import aiohttp.client
except ImportError as e:  # pragma: no cover
    raise SystemExit("aiohttp is required: pip install aiohttp") from e

GATEWAY_SCHEME = "http"
GATEWAY_HOST = "127.0.0.1"
GATEWAY_PORT = 18790
GATEWAY_BASE = f"{GATEWAY_SCHEME}://{GATEWAY_HOST}:{GATEWAY_PORT}"
LISTEN_HOST = "0.0.0.0"
LISTEN_PORT = 8443

CLARITY_DIR = Path(".clarity")
CERT_FILE = CLARITY_DIR / "localhost.crt"
KEY_FILE = CLARITY_DIR / "localhost.key"


def ensure_ssl_context() -> ssl.SSLContext:
    if not CERT_FILE.exists() or not KEY_FILE.exists():
        raise SystemExit(
            f"Certificate not found. Generate with:\n"
            f"  openssl req -x509 -newkey rsa:2048 -keyout {KEY_FILE} "
            f"-out {CERT_FILE} -days 365 -nodes -subj \"/CN=localhost\""
        )
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(certfile=str(CERT_FILE), keyfile=str(KEY_FILE))
    return ctx


async def proxy_http(request: web.Request) -> web.StreamResponse:
    """Proxy any non-WebSocket HTTP request to the Gateway."""
    target_url = f"{GATEWAY_BASE}{request.rel_url}"
    headers = {k: v for k, v in request.headers.items() if k.lower() != "host"}
    headers["Host"] = f"{GATEWAY_HOST}:{GATEWAY_PORT}"
    headers["X-Forwarded-Proto"] = "https"

    timeout = aiohttp.client.ClientTimeout(total=60)
    async with aiohttp.client.ClientSession(timeout=timeout) as session:
        try:
            async with session.request(
                method=request.method,
                url=target_url,
                headers=headers,
                data=request.content,
                allow_redirects=False,
            ) as upstream:
                response = web.StreamResponse(
                    status=upstream.status,
                    headers={k: v for k, v in upstream.headers.items()},
                )
                await response.prepare(request)
                async for chunk in upstream.content.iter_chunked(8192):
                    await response.write(chunk)
                await response.write_eof()
                return response
        except aiohttp.client.ClientConnectorError as e:
            return web.Response(status=502, text=f"Gateway unreachable: {e}")


async def proxy_ws(request: web.Request) -> web.WebSocketResponse:
    """Proxy a WebSocket connection to the Gateway."""
    ws_server = web.WebSocketResponse()
    await ws_server.prepare(request)

    target_url = f"ws://{GATEWAY_HOST}:{GATEWAY_PORT}{request.rel_url}"
    async with aiohttp.client.ClientSession() as session:
        async with session.ws_connect(target_url) as ws_client:
            async def server_to_client() -> None:
                async for msg in ws_server:
                    if msg.type == WSMsgType.TEXT:
                        await ws_client.send_str(msg.data)
                    elif msg.type == WSMsgType.BINARY:
                        await ws_client.send_bytes(msg.data)
                    elif msg.type == WSMsgType.CLOSE:
                        await ws_client.close()

            async def client_to_server() -> None:
                async for msg in ws_client:
                    if msg.type == WSMsgType.TEXT:
                        await ws_server.send_str(msg.data)
                    elif msg.type == WSMsgType.BINARY:
                        await ws_server.send_bytes(msg.data)
                    elif msg.type == WSMsgType.CLOSE:
                        await ws_server.close()

            await asyncio.gather(server_to_client(), client_to_server(), return_exceptions=True)

    return ws_server


async def route(request: web.Request) -> web.StreamResponse:
    """Route WebSocket upgrades to WS proxy, everything else to HTTP proxy."""
    upgrade = request.headers.get("Upgrade", "").lower()
    connection = request.headers.get("Connection", "").lower()
    if "websocket" in upgrade and "upgrade" in connection:
        return await proxy_ws(request)
    return await proxy_http(request)


async def main() -> int:
    CLARITY_DIR.mkdir(parents=True, exist_ok=True)
    ssl_ctx = ensure_ssl_context()

    app = web.Application()
    app.router.add_route("*", "/{path:.*}", route)

    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, LISTEN_HOST, LISTEN_PORT, ssl_context=ssl_ctx)
    await site.start()

    print(f"HTTPS/WSS reverse proxy listening on https://{LISTEN_HOST}:{LISTEN_PORT}")
    print(f"Forwarding to Gateway at {GATEWAY_BASE}")
    print("Try: curl -k https://localhost:8443/health")
    print("Try: wscat -k -c wss://localhost:8443/openclaw/ws")

    try:
        await asyncio.Future()  # run forever
    finally:
        await runner.cleanup()
    return 0


if __name__ == "__main__":
    try:
        sys.exit(asyncio.run(main()))
    except KeyboardInterrupt:
        print("\nShutting down TLS proxy.")
