//! # Clarity Mobile Core
//!
//! Mobile FFI layer for Project Clarity.
//!
//! This crate wraps the existing Rust engine (`clarity-core`, `clarity-wire`,
//! `clarity-memory`) and exposes a thin UniFFI surface to Android (Kotlin)
//! and iOS (Swift).
//!
//! # Safety note
//!
//! UniFFI-generated scaffolding exports `#[no_mangle]` FFI symbols, which are
//! unsafe under Rust 2024. This crate is the intentional FFI boundary; unsafe
//! code is generated by `uniffi-bindgen`, not hand-written.
#![allow(unsafe_code)]
// MobileRuntime::new is an FFI constructor; on mobile, startup failures are
// treated as fatal, so intentional panics remain in this crate-level boundary.
#![allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]

uniffi::include_scaffolding!("clarity_mobile_core");

use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use chrono::Utc;
use clarity_contract::ApprovalMode;
use clarity_core::agent::{Agent, AgentConfig, LlmProvider};
use clarity_core::registry::ToolRegistry;
use clarity_llm::{AnthropicLlm, DeepSeekProvider, KimiLlm, OpenAiCompatibleLlm};
use clarity_memory::SessionStore;
use clarity_wire::{Wire, WireMessage};
use parking_lot::Mutex;
use tokio::runtime::Runtime;
use uuid::Uuid;

/// Supported cloud LLM providers.
#[derive(Clone, Debug)]
pub enum ProviderType {
    /// OpenAI-compatible provider.
    OpenAi,
    /// Moonshot Kimi.
    Kimi,
    /// DeepSeek.
    Deepseek,
    /// Anthropic Claude.
    Anthropic,
}

/// LLM provider profile supplied by the host mobile OS.
#[derive(Clone, Debug)]
pub struct ProviderProfile {
    /// Which provider to use.
    pub provider: ProviderType,
    /// Model name, e.g. "gpt-4o" or "kimi-k2.6".
    pub model: String,
    /// API key for authentication.
    pub api_key: String,
    /// Optional custom base URL.
    pub base_url: Option<String>,
}

/// Runtime configuration passed from the host mobile OS.
#[derive(Clone, Debug)]
pub struct MobileConfig {
    /// Absolute path to the app's private data directory.
    pub data_dir: String,
    /// Default provider profile used for new conversations.
    pub default_provider: ProviderProfile,
}

/// Summary of a conversation thread.
#[derive(Clone, Debug)]
pub struct ThreadSummary {
    /// Thread identifier (UUID).
    pub thread_id: String,
    /// Optional human-readable title.
    pub title: Option<String>,
    /// ISO-8601 update timestamp.
    pub updated_at: String,
}

/// Events flowing from the Rust core to the mobile UI.
#[derive(Clone, Debug)]
pub enum UiEvent {
    /// A new turn has started.
    TurnBegin {
        /// Turn identifier.
        turn_id: String,
        /// User input text.
        user_input: String,
    },
    /// A text chunk from the assistant (streaming).
    ContentPart {
        /// Turn identifier.
        turn_id: String,
        /// Text chunk.
        text: String,
    },
    /// The model wants to call a tool.
    ToolCall {
        /// Turn identifier.
        turn_id: String,
        /// Tool call identifier.
        id: String,
        /// Tool name.
        name: String,
        /// JSON-encoded arguments.
        arguments_json: String,
    },
    /// A tool finished executing.
    ToolResult {
        /// Turn identifier.
        turn_id: String,
        /// Tool call identifier.
        id: String,
        /// JSON-encoded result.
        result_json: String,
    },
    /// The current turn finished.
    TurnEnd {
        /// Turn identifier.
        turn_id: String,
    },
    /// Token usage report for the turn.
    Usage {
        /// Turn identifier.
        turn_id: String,
        /// Prompt token count.
        prompt_tokens: u32,
        /// Completion token count.
        completion_tokens: u32,
    },
    /// Status update for the user (e.g. "thinking...").
    StatusUpdate {
        /// Turn identifier.
        turn_id: String,
        /// Status message.
        message: String,
    },
    /// The active thread has changed.
    ThreadActive {
        /// Thread identifier.
        thread_id: String,
        /// Optional title.
        title: Option<String>,
    },
    /// Something went wrong.
    Error {
        /// Error code.
        code: String,
        /// Human-readable error message.
        message: String,
    },
}

/// A handle to the mobile Clarity runtime.
///
/// All FFI calls go through this object. The internal state is kept opaque to
/// mobile consumers; they only send commands and poll events.
pub struct MobileRuntime {
    /// Tokio runtime for async operations.
    rt: Arc<Runtime>,
    /// The core Agent.
    agent: Arc<Agent>,
    /// Wire for soul → UI events.
    wire: Arc<Wire>,
    /// Local session store for conversation history.
    session_store: SessionStore,
    /// Currently active thread id.
    current_thread_id: Mutex<String>,
    /// Receiver for UI events produced by the event forwarder task.
    event_rx: Mutex<tokio::sync::mpsc::Receiver<UiEvent>>,
}

impl MobileRuntime {
    /// Create a new runtime instance.
    ///
    /// # Panics
    ///
    /// Panics if the tokio runtime, data directory, or session store cannot be
    /// initialized. Mobile callers should treat this as a fatal startup failure.
    pub fn new(config: MobileConfig) -> Self {
        let data_dir = PathBuf::from(&config.data_dir);
        std::fs::create_dir_all(&data_dir)
            .unwrap_or_else(|e| panic!("Failed to create data dir {}: {}", data_dir.display(), e));

        let rt = Arc::new(
            Runtime::new().unwrap_or_else(|e| panic!("Failed to create tokio runtime: {}", e)),
        );

        let wire = Arc::new(Wire::new());
        let provider = build_provider(&config.default_provider)
            .unwrap_or_else(|e| panic!("Failed to build default LLM provider: {}", e));

        // Mobile MVP: no file-system tools. The agent runs in chat-only mode.
        let registry = ToolRegistry::new();
        let agent_config = AgentConfig::new()
            .with_max_iterations(5)
            .with_working_dir(data_dir.clone());
        let agent = Arc::new(
            Agent::with_config(registry, agent_config)
                .with_llm(provider)
                .with_approval_mode(ApprovalMode::Yolo)
                .with_wire(wire.clone()),
        );

        let sessions_dir = data_dir.join("sessions");
        std::fs::create_dir_all(&sessions_dir).unwrap_or_else(|e| {
            panic!(
                "Failed to create sessions dir {}: {}",
                sessions_dir.display(),
                e
            )
        });
        let session_store = SessionStore::new(&sessions_dir)
            .unwrap_or_else(|e| panic!("Failed to create session store: {}", e));

        // Spawn a task that forwards WireMessages to a bounded channel consumed
        // by the mobile UI via [poll_event].
        let (event_tx, event_rx) = tokio::sync::mpsc::channel(256);
        let mut ui_side = wire.ui_side(true);
        rt.spawn(async move {
            while let Some(msg) = ui_side.recv().await {
                if let Some(event) = map_wire_message(msg) {
                    if event_tx.send(event).await.is_err() {
                        break;
                    }
                }
            }
        });

        Self {
            rt,
            agent,
            wire,
            session_store,
            current_thread_id: Mutex::new(String::new()),
            event_rx: Mutex::new(event_rx),
        }
    }

    /// Return the crate version.
    pub fn version(&self) -> String {
        env!("CARGO_PKG_VERSION").to_string()
    }

    /// Return a human-readable runtime version string.
    pub fn runtime_version(&self) -> String {
        format!("clarity-mobile-core v{}", self.version())
    }

    /// Create a new conversation thread.
    ///
    /// The session file is created lazily on first message; this only returns a
    /// new UUID and makes it the active thread.
    pub fn create_thread(&self, title: Option<String>) -> String {
        let thread_id = Uuid::new_v4().to_string();
        let _ = title; // titles stored in a future iteration
        self.switch_thread(thread_id.clone());
        thread_id
    }

    /// List existing threads, most recently updated first.
    pub fn list_threads(&self) -> Vec<ThreadSummary> {
        let ids = self.session_store.get_session_ids();
        let mut summaries = Vec::new();
        for id in ids {
            let messages = self.session_store.get_messages(&id).unwrap_or_default();
            let updated_at = messages
                .last()
                .map(|m| m.timestamp.to_rfc3339())
                .unwrap_or_else(|| Utc::now().to_rfc3339());
            summaries.push(ThreadSummary {
                thread_id: id,
                title: None,
                updated_at,
            });
        }
        summaries.sort_by(|a, b| b.updated_at.cmp(&a.updated_at));
        summaries
    }

    /// Switch the active thread.
    pub fn switch_thread(&self, thread_id: String) {
        // Tracked: github.com/juice094/clarity/issues — load thread history into agent context.
        *self.current_thread_id.lock() = thread_id.clone();
        self.wire
            .soul_side()
            .send(WireMessage::ThreadActive {
                thread_id,
                title: None,
            })
            .ok();
    }

    /// Get the active thread id.
    pub fn current_thread_id(&self) -> String {
        self.current_thread_id.lock().clone()
    }

    /// Update the LLM provider used for subsequent turns.
    pub fn set_provider(&self, profile: ProviderProfile) {
        let provider = match build_provider(&profile) {
            Ok(p) => p,
            Err(e) => {
                tracing::error!("Failed to build LLM provider: {}", e);
                return;
            }
        };
        self.agent.set_llm(provider);
    }

    /// Send a user message in the active thread.
    ///
    /// The response is delivered asynchronously via [`Self::poll_event`].
    pub fn send_message(&self, content: String) {
        let thread_id = self.current_thread_id.lock().clone();
        if thread_id.is_empty() {
            tracing::error!("send_message called with no active thread");
            return;
        }

        if let Err(e) = self
            .session_store
            .append_message(&thread_id, "user", &content)
        {
            tracing::error!("Failed to append user message: {}", e);
            return;
        }

        let agent = self.agent.clone();
        self.rt.spawn(async move {
            let result = agent.run(&content).await;
            if let Err(e) = result {
                tracing::error!("Agent run failed: {}", e);
            }
            // The returned string is also emitted through the Wire, so the UI
            // gets streaming content; we intentionally ignore it here.
        });
    }

    /// Poll for the next UI event.
    ///
    /// Blocks up to `timeout_ms` milliseconds. Returns `None` if no event
    /// arrived before the timeout.
    pub fn poll_event(&self, timeout_ms: u64) -> Option<UiEvent> {
        let mut rx = self.event_rx.lock();
        self.rt.block_on(async {
            tokio::time::timeout(Duration::from_millis(timeout_ms), rx.recv())
                .await
                .ok()
                .flatten()
        })
    }
}

/// Build an LLM provider from a mobile profile.
fn build_provider(profile: &ProviderProfile) -> anyhow::Result<Arc<dyn LlmProvider>> {
    let provider: Arc<dyn LlmProvider> = match profile.provider {
        ProviderType::OpenAi => {
            let base_url = profile
                .base_url
                .clone()
                .unwrap_or_else(|| "https://api.openai.com/v1".into());
            Arc::new(OpenAiCompatibleLlm::new(
                profile.api_key.clone(),
                base_url,
                profile.model.clone(),
            ))
        }
        ProviderType::Kimi => {
            let base_url = profile
                .base_url
                .clone()
                .unwrap_or_else(|| "https://api.moonshot.ai/v1".into());
            Arc::new(KimiLlm::new(
                profile.api_key.clone(),
                base_url,
                profile.model.clone(),
            ))
        }
        ProviderType::Deepseek => {
            let base_url = profile
                .base_url
                .clone()
                .unwrap_or_else(|| "https://api.deepseek.com/v1".into());
            Arc::new(DeepSeekProvider::new(
                profile.api_key.clone(),
                base_url,
                profile.model.clone(),
            ))
        }
        ProviderType::Anthropic => {
            let base_url = profile
                .base_url
                .clone()
                .unwrap_or_else(|| "https://api.anthropic.com".into());
            Arc::new(AnthropicLlm::new(
                profile.api_key.clone(),
                base_url,
                profile.model.clone(),
            ))
        }
    };
    Ok(provider)
}

/// Map a raw [WireMessage] to a mobile-friendly [UiEvent].
#[allow(unreachable_patterns)] // `_` catch-all is intentional for future variants
fn map_wire_message(msg: WireMessage) -> Option<UiEvent> {
    Some(match msg {
        WireMessage::TurnBegin {
            turn_id,
            user_input,
        } => UiEvent::TurnBegin {
            turn_id,
            user_input,
        },
        WireMessage::ContentPart { turn_id, text } => UiEvent::ContentPart { turn_id, text },
        WireMessage::ReasoningPart { turn_id, text } => UiEvent::ContentPart { turn_id, text },
        WireMessage::ToolCall {
            turn_id,
            id,
            name,
            arguments,
        } => UiEvent::ToolCall {
            turn_id,
            id,
            name,
            arguments_json: arguments.to_string(),
        },
        WireMessage::ToolResult {
            turn_id,
            id,
            result,
            ..
        } => UiEvent::ToolResult {
            turn_id,
            id,
            result_json: result,
        },
        WireMessage::TurnEnd { turn_id } => UiEvent::TurnEnd { turn_id },
        WireMessage::Usage {
            turn_id,
            prompt_tokens,
            completion_tokens,
            ..
        } => UiEvent::Usage {
            turn_id,
            prompt_tokens,
            completion_tokens,
        },
        WireMessage::StatusUpdate { turn_id, message } => {
            UiEvent::StatusUpdate { turn_id, message }
        }
        WireMessage::ThreadActive { thread_id, title } => {
            UiEvent::ThreadActive { thread_id, title }
        }
        WireMessage::DraftEvent { turn_id, event } => match event {
            clarity_wire::DraftEvent::Clear => return None,
            clarity_wire::DraftEvent::Progress { text } => UiEvent::StatusUpdate {
                turn_id,
                message: text,
            },
            clarity_wire::DraftEvent::Content { text } => UiEvent::ContentPart { turn_id, text },
        },
        // Variants not needed for the mobile chat UI are dropped.
        WireMessage::StepBegin { .. }
        | WireMessage::ToolCallProgress { .. }
        | WireMessage::PlanStepBegin { .. }
        | WireMessage::PlanStepEnd { .. }
        | WireMessage::PlanStepSkipped { .. }
        | WireMessage::CompactionBegin { .. }
        | WireMessage::CompactionEnd { .. }
        | WireMessage::ThreadList { .. }
        | WireMessage::ThreadCreated { .. }
        | WireMessage::ThreadUpdated { .. }
        | WireMessage::ViewStateUpdate { .. } => return None,
        _ => return None,
    })
}

/// Returns the global runtime version string without needing a runtime handle.
pub fn runtime_version() -> String {
    format!("clarity-mobile-core v{}", env!("CARGO_PKG_VERSION"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_runtime_version() {
        let v = runtime_version();
        assert!(v.starts_with("clarity-mobile-core v"));
        assert!(v.contains(env!("CARGO_PKG_VERSION")));
    }

    #[test]
    fn test_map_wire_message_turn_begin() {
        let msg = WireMessage::TurnBegin {
            turn_id: "t1".into(),
            user_input: "hello".into(),
        };
        let event = map_wire_message(msg).expect("mapped");
        assert!(
            matches!(event, UiEvent::TurnBegin { turn_id, user_input } if turn_id == "t1" && user_input == "hello")
        );
    }

    #[test]
    fn test_map_wire_message_content_part() {
        let msg = WireMessage::ContentPart {
            turn_id: "t1".into(),
            text: "world".into(),
        };
        let event = map_wire_message(msg).expect("mapped");
        assert!(
            matches!(event, UiEvent::ContentPart { turn_id, text } if turn_id == "t1" && text == "world")
        );
    }
}
