//! Semantic line model for chat content — ADR-012 implementation.
//!
//! Replaces pixel-continuous markdown streams with discrete typed lines.
//! Each line carries enough structural information for both GUI (egui)
//! and TUI (ratatui) renderers to produce correct output without re-parsing.
//!
//! ## Design principles
//!
//! - **Line-atomic**: The smallest unit of rendering is one line. Virtual scrolling,
//!   j/k navigation, and streaming append all operate on `Vec<RenderLine>`.
//! - **Frontend-neutral**: No egui or ratatui types leak into this module.
//! - **Graceful degradation**: Complex blocks (tables, images, full-screen Plan)
//!   fall back to `BlockSlot` and are rendered by the existing block pipeline.

use serde::{Deserialize, Serialize};
use smol_str::SmolStr;

// ============================================================================
// Line model
// ============================================================================

/// A single semantic line in the chat stream.
///
/// 13 variants absorb 30+ markdown / UI patterns per ADR-012.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "kind", content = "value")]
pub enum RenderLine {
    /// Plain text with optional inline spans and semantic role.
    Text {
        spans: Vec<Span>,
        role: LineRole,
        indent: u8,
    },

    /// One line inside a fenced code block.
    CodeLine {
        lang: SmolStr,
        content: SmolStr,
        line_no: Option<u32>,
        diff: DiffKind,
    },

    /// Header line for a tool call block (expandable).
    ToolCallHeader {
        name: SmolStr,
        status: ToolStatus,
        expanded: bool,
    },

    /// A single argument row inside an expanded tool call.
    ToolCallArg {
        key: SmolStr,
        value: SmolStr,
    },

    /// Collapsible thinking / reasoning block (ClaudeCode-borrowed).
    Thinking {
        content: SmolStr,
        collapsed: bool,
    },

    /// Interactive approval prompt with options.
    ApprovalPrompt {
        options: Vec<ApprovalOption>,
    },

    /// Transient or persistent status indicator (spinner, progress, network).
    StatusLine {
        kind: StatusKind,
        content: SmolStr,
        transient: bool,
    },

    /// Reference to an Artifact (ClaudeCode-borrowed, rendered as a card).
    ArtifactRef {
        artifact_id: ArtifactId,
        summary: SmolStr,
    },

    /// Cross-instance mention — clicking navigates to the target instance/session.
    CrossInstanceRef {
        target_instance: InstanceId,
        target_session: Option<SessionId>,
        message: SmolStr,
    },

    /// Slash-command autocomplete suggestion row.
    SlashCompletion {
        command: SmolStr,
        description: SmolStr,
    },

    /// Blinking cursor at the end of a streaming response.
    StreamingCursor,

    /// Horizontal rule (--- or *** in markdown).
    Divider,

    /// Empty line — preserves vertical spacing from the original markdown.
    Empty,

    /// Escape hatch for blocks that cannot be line-atomised (tables, images, Plan).
    /// The frontend delegates to the existing `RenderBlock` pipeline.
    BlockSlot {
        block_id: BlockId,
        line_count: u8,
    },
}

/// Inline text span with a semantic style tag.
///
/// Frontends map `SpanStyle` to concrete colors/fonts via their theme system.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Span {
    pub text: SmolStr,
    pub style: SpanStyle,
}

impl Span {
    pub fn plain(text: impl Into<SmolStr>) -> Self {
        Self {
            text: text.into(),
            style: SpanStyle::Normal,
        }
    }

    pub fn styled(text: impl Into<SmolStr>, style: SpanStyle) -> Self {
        Self {
            text: text.into(),
            style,
        }
    }
}

/// Semantic style tags for inline spans.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SpanStyle {
    Normal,
    Bold,
    Italic,
    BoldItalic,
    Code,
    Link,
    Mention,   // @user / @instance
    FileRef,   // @path/to/file
    Highlight, // search match / selection
}

/// The "voice" or structural role of a line.
///
/// Determines left-margin treatment, icon, and color baseline in the renderer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "kind", content = "value")]
pub enum LineRole {
    /// Message sent by the user.
    UserMessage,
    /// Message generated by the agent.
    AgentMessage,
    /// System notice (errors, warnings from the runtime).
    SystemMessage,
    /// Explicit error output.
    ErrorMessage,
    /// Markdown heading level 1–6.
    Heading(u8),
    /// Blockquote line.
    Quote,
    /// Bullet list item at a given indent depth (0 = top level).
    UnorderedListItem(u8),
    /// Numbered list item.
    OrderedListItem { num: u32, indent: u8 },
    /// @-mention of a user or instance.
    Mention,
    /// File path reference.
    FileRef,
    /// Informative status line.
    Status,
    /// Warning line.
    Warning,
    /// Contextual note.
    Note,
    /// Token usage summary (e.g. "47K / 200K").
    TokenUsage,
    /// Context compaction notice.
    ContextCompaction,
    /// openclaw-compatible sandbox indicator.
    Sandbox,
}

/// Diff kind for code lines (Git-style hunk rendering).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DiffKind {
    #[default]
    Normal,
    Added,
    Removed,
    Context,
}

/// Tool call lifecycle status.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolStatus {
    Running,
    Success,
    Warning,
    Error,
}

/// Status indicator kind for `StatusLine`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "kind", content = "value")]
pub enum StatusKind {
    Spinner,
    Progress { current: u32, total: u32 },
    Network,
    Compaction,
    ModelSwitch,
}

/// Interactive approval option (1/2/3 key selection).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "kind", content = "value")]
pub enum ApprovalOption {
    Yes,
    YesAndRemember,
    No { reason_required: bool },
    Custom(SmolStr),
}

// ============================================================================
// Type aliases — identity types for cross-instance and artifact references
// ============================================================================

pub type ArtifactId = SmolStr;
pub type InstanceId = SmolStr;
pub type SessionId = SmolStr;
pub type BlockId = SmolStr;

// ============================================================================
// Markdown → Lines converter
// ============================================================================

/// Convert a markdown string into a sequence of `RenderLine`s.
///
/// This is a **lossy** conversion in one direction: tables and images degrade
/// to `BlockSlot`, and complex nested HTML is stripped. The goal is to produce
/// a line stream that covers 90 % of real agent output (headings, lists, code,
/// paragraphs, blockquotes) while delegating the remainder to the block pipeline.
///
/// ## Streaming readiness
///
/// The converter operates on complete markdown chunks. For streaming, the
/// caller buffers until a natural boundary (newline, closing fence, end of
/// block element) and re-parses the accumulated chunk. `StreamingCursor` is
/// appended manually by the frontend between flushes.
pub fn markdown_to_lines(md: &str) -> Vec<RenderLine> {
    use pulldown_cmark::{Event, Parser, Tag, TagEnd};

    let mut lines: Vec<RenderLine> = Vec::new();
    let mut current_text = String::new();
    let mut in_code_block = false;
    let mut code_lang = SmolStr::default();
    let mut code_lines: Vec<String> = Vec::new();
    let mut list_stack: Vec<u8> = Vec::new(); // indent depths
    let mut ordered_num: u32 = 0;
    let mut heading_level: u8;
    let mut role_stack: Vec<LineRole> = Vec::new();
    let mut current_role = LineRole::AgentMessage;

    let flush_with_role = |buf: &mut String, out: &mut Vec<RenderLine>, role: LineRole, indent: u8| {
        if !buf.trim().is_empty() {
            out.push(RenderLine::Text {
                spans: vec![Span::plain(std::mem::take(buf))],
                role,
                indent,
            });
        } else if !buf.is_empty() {
            out.push(RenderLine::Empty);
        }
        buf.clear();
    };

    let parser = Parser::new(md);
    for event in parser {
        match event {
            Event::Start(Tag::CodeBlock(lang)) => {
                flush_with_role(&mut current_text, &mut lines, current_role, 0);
                in_code_block = true;
                code_lang = match lang {
                    pulldown_cmark::CodeBlockKind::Fenced(l) => l.to_string().into(),
                    pulldown_cmark::CodeBlockKind::Indented => SmolStr::default(),
                };
                code_lines.clear();
            }
            Event::End(TagEnd::CodeBlock) => {
                in_code_block = false;
                // Filter trailing empty lines produced by terminal newlines.
                while let Some(last) = code_lines.last() {
                    if last.trim().is_empty() {
                        code_lines.pop();
                    } else {
                        break;
                    }
                }
                for (i, content) in code_lines.iter().enumerate() {
                    lines.push(RenderLine::CodeLine {
                        lang: code_lang.clone(),
                        content: content.clone().into(),
                        line_no: Some((i + 1) as u32),
                        diff: DiffKind::Normal,
                    });
                }
                code_lines.clear();
                code_lang = SmolStr::default();
            }
            Event::Start(Tag::List(start_num)) => {
                flush_with_role(&mut current_text, &mut lines, current_role, 0);
                list_stack.push(list_stack.last().copied().unwrap_or(0) + 1);
                ordered_num = start_num.map(|n| n as u32).unwrap_or(0);
            }
            Event::End(TagEnd::List(_)) => {
                list_stack.pop();
            }
            Event::Start(Tag::Item) => {
                role_stack.push(current_role);
                let depth = list_stack.last().copied().unwrap_or(0).saturating_sub(1);
                current_role = if ordered_num > 0 {
                    let num = ordered_num;
                    ordered_num += 1;
                    LineRole::OrderedListItem { num, indent: depth }
                } else {
                    LineRole::UnorderedListItem(depth)
                };
            }
            Event::End(TagEnd::Item) => {
                flush_with_role(&mut current_text, &mut lines, current_role, 0);
                current_role = role_stack.pop().unwrap_or(LineRole::AgentMessage);
            }
            Event::Start(Tag::Heading { level, .. }) => {
                flush_with_role(&mut current_text, &mut lines, current_role, 0);
                role_stack.push(current_role);
                heading_level = level as u8;
                current_role = LineRole::Heading(heading_level);
            }
            Event::End(TagEnd::Heading(_)) => {
                flush_with_role(&mut current_text, &mut lines, current_role, 0);
                current_role = role_stack.pop().unwrap_or(LineRole::AgentMessage);
            }
            Event::Start(Tag::BlockQuote(_)) => {
                flush_with_role(&mut current_text, &mut lines, current_role, 0);
                role_stack.push(current_role);
                current_role = LineRole::Quote;
            }
            Event::End(TagEnd::BlockQuote(_)) => {
                flush_with_role(&mut current_text, &mut lines, current_role, 0);
                current_role = role_stack.pop().unwrap_or(LineRole::AgentMessage);
            }
            Event::Start(Tag::Paragraph) => {
                // Paragraphs are the default; no role change needed.
            }
            Event::End(TagEnd::Paragraph) => {
                flush_with_role(&mut current_text, &mut lines, current_role, 0);
            }
            Event::Text(t) | Event::Code(t) => {
                if in_code_block {
                    for line in t.split('\n') {
                        code_lines.push(line.to_string());
                    }
                } else {
                    current_text.push_str(&t);
                }
            }
            Event::SoftBreak | Event::HardBreak if !in_code_block => {
                flush_with_role(&mut current_text, &mut lines, current_role, 0);
            }
            Event::Rule => {
                flush_with_role(&mut current_text, &mut lines, current_role, 0);
                lines.push(RenderLine::Divider);
            }
            Event::Html(html) => {
                current_text.push_str(&html);
            }
            _ => {
                // Inline formatting (Strong, Emphasis, Link, etc.) is flattened
                // to plain text in the skeleton; S5 (renderer) introduces Span
                // style extraction from the event stream.
            }
        }
    }

    flush_with_role(&mut current_text, &mut lines, current_role, 0);

    if lines.is_empty() {
        lines.push(RenderLine::Empty);
    }

    lines
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // ── Basic markdown patterns ──

    #[test]
    fn empty_input_yields_empty_line() {
        let lines = markdown_to_lines("");
        assert_eq!(lines.len(), 1);
        assert!(matches!(lines[0], RenderLine::Empty));
    }

    #[test]
    fn plain_paragraph() {
        let lines = markdown_to_lines("Hello world");
        assert_eq!(lines.len(), 1);
        assert!(matches!(&lines[0], RenderLine::Text { role: LineRole::AgentMessage, spans, .. } if spans.len() == 1));
    }

    #[test]
    fn two_paragraphs() {
        let lines = markdown_to_lines("First para.\n\nSecond para.");
        assert_eq!(lines.len(), 2);
        assert!(matches!(&lines[0], RenderLine::Text { .. }));
        assert!(matches!(&lines[1], RenderLine::Text { .. }));
    }

    #[test]
    fn headings_all_levels() {
        let md = "# H1\n## H2\n### H3\n#### H4\n##### H5\n###### H6";
        let lines = markdown_to_lines(md);
        assert_eq!(lines.len(), 6);
        for (i, line) in lines.iter().enumerate() {
            let expected_level = (i + 1) as u8;
            assert!(
                matches!(line, RenderLine::Text { role: LineRole::Heading(l), .. } if *l == expected_level),
                "line {i} should be Heading({expected_level})"
            );
        }
    }

    #[test]
    fn unordered_list() {
        let md = "- alpha\n- beta\n- gamma";
        let lines = markdown_to_lines(md);
        assert_eq!(lines.len(), 3);
        for line in &lines {
            assert!(matches!(line, RenderLine::Text { role: LineRole::UnorderedListItem(0), .. }));
        }
    }

    #[test]
    fn ordered_list() {
        let md = "1. first\n2. second\n3. third";
        let lines = markdown_to_lines(md);
        assert_eq!(lines.len(), 3);
        for (i, line) in lines.iter().enumerate() {
            let expected_num = (i + 1) as u32;
            assert!(
                matches!(line, RenderLine::Text { role: LineRole::OrderedListItem { num, indent: 0 }, .. } if *num == expected_num)
            );
        }
    }

    #[test]
    fn code_block_with_lang() {
        let md = "```rust\nlet x = 1;\nlet y = 2;\n```";
        let lines = markdown_to_lines(md);
        assert_eq!(lines.len(), 2);
        assert!(matches!(&lines[0], RenderLine::CodeLine { lang, content, line_no: Some(1), .. }
            if lang == "rust" && content == "let x = 1;"
        ));
        assert!(matches!(&lines[1], RenderLine::CodeLine { lang, content, line_no: Some(2), .. }
            if lang == "rust" && content == "let y = 2;"
        ));
    }

    #[test]
    fn code_block_without_lang() {
        let md = "```\nplain text\n```";
        let lines = markdown_to_lines(md);
        assert_eq!(lines.len(), 1);
        assert!(matches!(&lines[0], RenderLine::CodeLine { lang, content, .. }
            if lang.is_empty() && content == "plain text"
        ));
    }

    #[test]
    fn blockquote() {
        let md = "> quoted text";
        let lines = markdown_to_lines(md);
        assert_eq!(lines.len(), 1);
        assert!(matches!(&lines[0], RenderLine::Text { role: LineRole::Quote, .. }));
    }

    #[test]
    fn horizontal_rule() {
        let md = "foo\n\n---\n\nbar";
        let lines = markdown_to_lines(md);
        assert!(lines.iter().any(|l| matches!(l, RenderLine::Divider)));
    }

    #[test]
    fn mixed_document() {
        let md = r#"# Title

Some intro.

```python
print("hi")
```

- item one
- item two

> a quote

Final words."#;
        let lines = markdown_to_lines(md);

        // Spot-check structural expectations without asserting exact counts
        // (pulldown-cmark event ordering may introduce minor Empty lines).
        assert!(lines.iter().any(|l| matches!(l, RenderLine::Text { role: LineRole::Heading(1), .. })));
        assert!(lines.iter().any(|l| matches!(l, RenderLine::CodeLine { lang, .. } if lang == "python")));
        assert!(lines.iter().any(|l| matches!(l, RenderLine::Text { role: LineRole::UnorderedListItem(0), .. })));
        assert!(lines.iter().any(|l| matches!(l, RenderLine::Text { role: LineRole::Quote, .. })));
        assert!(lines.iter().any(|l| matches!(l, RenderLine::Text { role: LineRole::AgentMessage, .. })));
    }

    // ── Variant constructors ──

    #[test]
    fn render_line_variants_roundtrip_via_json() {
        let lines = vec![
            RenderLine::Text {
                spans: vec![Span::plain("hello"), Span::styled("world", SpanStyle::Bold)],
                role: LineRole::AgentMessage,
                indent: 0,
            },
            RenderLine::CodeLine {
                lang: "rust".into(),
                content: "let x = 1;".into(),
                line_no: Some(1),
                diff: DiffKind::Added,
            },
            RenderLine::ToolCallHeader {
                name: "bash".into(),
                status: ToolStatus::Running,
                expanded: false,
            },
            RenderLine::ApprovalPrompt {
                options: vec![
                    ApprovalOption::Yes,
                    ApprovalOption::No { reason_required: false },
                ],
            },
            RenderLine::StatusLine {
                kind: StatusKind::Progress { current: 3, total: 10 },
                content: "Indexing...".into(),
                transient: true,
            },
            RenderLine::StreamingCursor,
            RenderLine::Divider,
            RenderLine::Empty,
        ];

        for line in &lines {
            let json = serde_json::to_string(line).unwrap();
            let restored: RenderLine = serde_json::from_str(&json).unwrap();
            assert_eq!(*line, restored, "roundtrip failed for {line:?}");
        }
    }

    #[test]
    fn block_slot_roundtrip() {
        let line = RenderLine::BlockSlot {
            block_id: "table-1".into(),
            line_count: 5,
        };
        let json = serde_json::to_string(&line).unwrap();
        let restored: RenderLine = serde_json::from_str(&json).unwrap();
        assert_eq!(line, restored);
    }

    #[test]
    fn span_construction_helpers() {
        let s1 = Span::plain("hello");
        assert_eq!(s1.text, "hello");
        assert_eq!(s1.style, SpanStyle::Normal);

        let s2 = Span::styled("bold", SpanStyle::Bold);
        assert_eq!(s2.text, "bold");
        assert_eq!(s2.style, SpanStyle::Bold);
    }
}
